name: Java CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  test:

    name: Test
    runs-on: macOS-latest

    strategy:
      max-parallel: 6
      matrix:
        # List all schemes to build
        scheme: [blank, blankTests, blankUITests]
        # Specify the platform & devices
        platform: [iOS Simulator]
        device: [iPhone Xs, iPhone Xs Max]

    steps:

      - uses: actions/checkout@v1

        # Runs if matrix.scheme is set to default
        # Finds the first listed scheme
      - name: Set Default Scheme
        if: matrix.scheme == 'default'
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")